# Generated by Django 2.2.26 on 2022-03-11 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0002_auto_20220311_0030'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comment',
            name='%(app_label)s_%(class)s_rating_range',
        ),
    ]
